[workspace]
resolver = "2"
members = ["crates/*", "xtask"]
default-members = ["crates/*"]

[workspace.package]
version = "1.1.0"
edition = "2024"
description = "Assembly implementation of the ArchP ISA"
homepage = "https://github.cim/PFiS1737/ISA-ArchP#readme"
repository = "https://github.cim/PFiS1737/ISA-ArchP"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
cc = { version = "1.0", features = ["parallel"] }
clap = { version = "4.6", features = ["derive"] }
clap_complete = { version = "4.6", features = ["unstable-dynamic"] }
colored = "3.0"
env_logger = "0.11"
insta = "1.48"
inventory = "0.3"
libc = "0.2"
log = "0.4"
nom = "8.0"
rand = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1.15"
tempfile = "3.27"
thiserror = "2.0"

archp_assembler = { path = "crates/archp_assembler" }

[profile.dev.package]
# https://insta.rs/docs/quickstart/#optional-faster-runs
insta.opt-level = 3
similar.opt-level = 3
