//! This file is @generated by [archp_codegen].
//! Do not edit it.
use crate::instructions::Instruction;
use crate::types::{InstructionType, OperandType};
pub static ADD: &Instruction = &Instruction {
    name: "add",
    opcode: 0u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SUB: &Instruction = &Instruction {
    name: "sub",
    opcode: 0u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static AND: &Instruction = &Instruction {
    name: "and",
    opcode: 0u32,
    funct3: 2u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static OR: &Instruction = &Instruction {
    name: "or",
    opcode: 0u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static ADDI: &Instruction = &Instruction {
    name: "addi",
    opcode: 0u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SUBI: &Instruction = &Instruction {
    name: "subi",
    opcode: 0u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static ANDI: &Instruction = &Instruction {
    name: "andi",
    opcode: 0u32,
    funct3: 6u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static ORI: &Instruction = &Instruction {
    name: "ori",
    opcode: 0u32,
    funct3: 7u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static XOR: &Instruction = &Instruction {
    name: "xor",
    opcode: 1u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static XNOR: &Instruction = &Instruction {
    name: "xnor",
    opcode: 1u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static NAND: &Instruction = &Instruction {
    name: "nand",
    opcode: 1u32,
    funct3: 2u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static NOR: &Instruction = &Instruction {
    name: "nor",
    opcode: 1u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static XORI: &Instruction = &Instruction {
    name: "xori",
    opcode: 1u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static XNORI: &Instruction = &Instruction {
    name: "xnori",
    opcode: 1u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static NANDI: &Instruction = &Instruction {
    name: "nandi",
    opcode: 1u32,
    funct3: 6u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static NORI: &Instruction = &Instruction {
    name: "nori",
    opcode: 1u32,
    funct3: 7u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static MUL: &Instruction = &Instruction {
    name: "mul",
    opcode: 2u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static MULH: &Instruction = &Instruction {
    name: "mulh",
    opcode: 2u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static MULHU: &Instruction = &Instruction {
    name: "mulhu",
    opcode: 2u32,
    funct3: 2u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static MULHSU: &Instruction = &Instruction {
    name: "mulhsu",
    opcode: 2u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static MULI: &Instruction = &Instruction {
    name: "muli",
    opcode: 2u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static MULHI: &Instruction = &Instruction {
    name: "mulhi",
    opcode: 2u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static MULHIU: &Instruction = &Instruction {
    name: "mulhiu",
    opcode: 2u32,
    funct3: 6u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static MULHISU: &Instruction = &Instruction {
    name: "mulhisu",
    opcode: 2u32,
    funct3: 7u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static DIV: &Instruction = &Instruction {
    name: "div",
    opcode: 3u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static REM: &Instruction = &Instruction {
    name: "rem",
    opcode: 3u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static DIVU: &Instruction = &Instruction {
    name: "divu",
    opcode: 3u32,
    funct3: 2u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static REMU: &Instruction = &Instruction {
    name: "remu",
    opcode: 3u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static DIVI: &Instruction = &Instruction {
    name: "divi",
    opcode: 3u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static REMI: &Instruction = &Instruction {
    name: "remi",
    opcode: 3u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static DIVIU: &Instruction = &Instruction {
    name: "diviu",
    opcode: 3u32,
    funct3: 6u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static REMIU: &Instruction = &Instruction {
    name: "remiu",
    opcode: 3u32,
    funct3: 7u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SLL: &Instruction = &Instruction {
    name: "sll",
    opcode: 4u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SRL: &Instruction = &Instruction {
    name: "srl",
    opcode: 4u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SRA: &Instruction = &Instruction {
    name: "sra",
    opcode: 4u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static ROL: &Instruction = &Instruction {
    name: "rol",
    opcode: 4u32,
    funct3: 4u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static ROR: &Instruction = &Instruction {
    name: "ror",
    opcode: 4u32,
    funct3: 5u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SLLI: &Instruction = &Instruction {
    name: "slli",
    opcode: 5u32,
    funct3: 0u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(5, false)],
};
pub static SRLI: &Instruction = &Instruction {
    name: "srli",
    opcode: 5u32,
    funct3: 1u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(5, false)],
};
pub static SRAI: &Instruction = &Instruction {
    name: "srai",
    opcode: 5u32,
    funct3: 3u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(5, false)],
};
pub static ROLI: &Instruction = &Instruction {
    name: "roli",
    opcode: 5u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(5, false)],
};
pub static RORI: &Instruction = &Instruction {
    name: "rori",
    opcode: 5u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(5, false)],
};
pub static SEQ: &Instruction = &Instruction {
    name: "seq",
    opcode: 6u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SNE: &Instruction = &Instruction {
    name: "sne",
    opcode: 6u32,
    funct3: 1u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SLT: &Instruction = &Instruction {
    name: "slt",
    opcode: 6u32,
    funct3: 2u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SGE: &Instruction = &Instruction {
    name: "sge",
    opcode: 6u32,
    funct3: 3u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SLTU: &Instruction = &Instruction {
    name: "sltu",
    opcode: 6u32,
    funct3: 4u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SGEU: &Instruction = &Instruction {
    name: "sgeu",
    opcode: 6u32,
    funct3: 5u32,
    itype: InstructionType::R,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::RegS],
};
pub static SEQI: &Instruction = &Instruction {
    name: "seqi",
    opcode: 7u32,
    funct3: 0u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SNEI: &Instruction = &Instruction {
    name: "snei",
    opcode: 7u32,
    funct3: 1u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SLTI: &Instruction = &Instruction {
    name: "slti",
    opcode: 7u32,
    funct3: 2u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SGEI: &Instruction = &Instruction {
    name: "sgei",
    opcode: 7u32,
    funct3: 3u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SLTIU: &Instruction = &Instruction {
    name: "sltiu",
    opcode: 7u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SGEIU: &Instruction = &Instruction {
    name: "sgeiu",
    opcode: 7u32,
    funct3: 5u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static LW: &Instruction = &Instruction {
    name: "lw",
    opcode: 8u32,
    funct3: 0u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static LH: &Instruction = &Instruction {
    name: "lh",
    opcode: 8u32,
    funct3: 1u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static LHU: &Instruction = &Instruction {
    name: "lhu",
    opcode: 8u32,
    funct3: 2u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static LB: &Instruction = &Instruction {
    name: "lb",
    opcode: 8u32,
    funct3: 3u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static LBU: &Instruction = &Instruction {
    name: "lbu",
    opcode: 8u32,
    funct3: 4u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SW: &Instruction = &Instruction {
    name: "sw",
    opcode: 8u32,
    funct3: 5u32,
    itype: InstructionType::S,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SH: &Instruction = &Instruction {
    name: "sh",
    opcode: 8u32,
    funct3: 6u32,
    itype: InstructionType::S,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static SB: &Instruction = &Instruction {
    name: "sb",
    opcode: 8u32,
    funct3: 7u32,
    itype: InstructionType::S,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static BEQ: &Instruction = &Instruction {
    name: "beq",
    opcode: 9u32,
    funct3: 0u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static BNE: &Instruction = &Instruction {
    name: "bne",
    opcode: 9u32,
    funct3: 1u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static BLT: &Instruction = &Instruction {
    name: "blt",
    opcode: 9u32,
    funct3: 2u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static BGE: &Instruction = &Instruction {
    name: "bge",
    opcode: 9u32,
    funct3: 3u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static BLTU: &Instruction = &Instruction {
    name: "bltu",
    opcode: 9u32,
    funct3: 4u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static BGEU: &Instruction = &Instruction {
    name: "bgeu",
    opcode: 9u32,
    funct3: 5u32,
    itype: InstructionType::B,
    format: &[OperandType::RegS, OperandType::RegS, OperandType::Addr(12)],
};
pub static JALR: &Instruction = &Instruction {
    name: "jalr",
    opcode: 9u32,
    funct3: 7u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::RegS, OperandType::Imm(12, true)],
};
pub static JAL: &Instruction = &Instruction {
    name: "jal",
    opcode: 10u32,
    funct3: 0u32,
    itype: InstructionType::J,
    format: &[OperandType::RegD, OperandType::Addr(20)],
};
pub static LUI: &Instruction = &Instruction {
    name: "lui",
    opcode: 11u32,
    funct3: 0u32,
    itype: InstructionType::U,
    format: &[OperandType::RegD, OperandType::Imm(20, false)],
};
pub static AUIPC: &Instruction = &Instruction {
    name: "auipc",
    opcode: 12u32,
    funct3: 0u32,
    itype: InstructionType::U,
    format: &[OperandType::RegD, OperandType::Imm(20, false)],
};
pub static ECALL: &Instruction = &Instruction {
    name: "ecall",
    opcode: 32u32,
    funct3: 0u32,
    itype: InstructionType::R,
    format: &[OperandType::None, OperandType::None, OperandType::None],
};
#[cfg(feature = "stack")]
pub static CALL: &Instruction = &Instruction {
    name: "call",
    opcode: 125u32,
    funct3: 0u32,
    itype: InstructionType::J,
    format: &[OperandType::None, OperandType::Addr(20)],
};
#[cfg(feature = "stack")]
pub static POP: &Instruction = &Instruction {
    name: "pop",
    opcode: 126u32,
    funct3: 0u32,
    itype: InstructionType::I,
    format: &[OperandType::RegD, OperandType::None, OperandType::None],
};
#[cfg(feature = "stack")]
pub static PUSH: &Instruction = &Instruction {
    name: "push",
    opcode: 126u32,
    funct3: 1u32,
    itype: InstructionType::I,
    format: &[OperandType::None, OperandType::RegS, OperandType::None],
};
#[cfg(feature = "stack")]
pub static RET: &Instruction = &Instruction {
    name: "ret",
    opcode: 126u32,
    funct3: 2u32,
    itype: InstructionType::I,
    format: &[OperandType::None, OperandType::None, OperandType::None],
};
#[cfg(feature = "stack")]
pub static CALLR: &Instruction = &Instruction {
    name: "callr",
    opcode: 126u32,
    funct3: 3u32,
    itype: InstructionType::I,
    format: &[OperandType::None, OperandType::RegS, OperandType::Imm(12, true)],
};
pub fn get_by_name(name: &str) -> Option<&'static Instruction> {
    match name {
        "add" => Some(ADD),
        "sub" => Some(SUB),
        "and" => Some(AND),
        "or" => Some(OR),
        "addi" => Some(ADDI),
        "subi" => Some(SUBI),
        "andi" => Some(ANDI),
        "ori" => Some(ORI),
        "xor" => Some(XOR),
        "xnor" => Some(XNOR),
        "nand" => Some(NAND),
        "nor" => Some(NOR),
        "xori" => Some(XORI),
        "xnori" => Some(XNORI),
        "nandi" => Some(NANDI),
        "nori" => Some(NORI),
        "mul" => Some(MUL),
        "mulh" => Some(MULH),
        "mulhu" => Some(MULHU),
        "mulhsu" => Some(MULHSU),
        "muli" => Some(MULI),
        "mulhi" => Some(MULHI),
        "mulhiu" => Some(MULHIU),
        "mulhisu" => Some(MULHISU),
        "div" => Some(DIV),
        "rem" => Some(REM),
        "divu" => Some(DIVU),
        "remu" => Some(REMU),
        "divi" => Some(DIVI),
        "remi" => Some(REMI),
        "diviu" => Some(DIVIU),
        "remiu" => Some(REMIU),
        "sll" => Some(SLL),
        "srl" => Some(SRL),
        "sra" => Some(SRA),
        "rol" => Some(ROL),
        "ror" => Some(ROR),
        "slli" => Some(SLLI),
        "srli" => Some(SRLI),
        "srai" => Some(SRAI),
        "roli" => Some(ROLI),
        "rori" => Some(RORI),
        "seq" => Some(SEQ),
        "sne" => Some(SNE),
        "slt" => Some(SLT),
        "sge" => Some(SGE),
        "sltu" => Some(SLTU),
        "sgeu" => Some(SGEU),
        "seqi" => Some(SEQI),
        "snei" => Some(SNEI),
        "slti" => Some(SLTI),
        "sgei" => Some(SGEI),
        "sltiu" => Some(SLTIU),
        "sgeiu" => Some(SGEIU),
        "lw" => Some(LW),
        "lh" => Some(LH),
        "lhu" => Some(LHU),
        "lb" => Some(LB),
        "lbu" => Some(LBU),
        "sw" => Some(SW),
        "sh" => Some(SH),
        "sb" => Some(SB),
        "beq" => Some(BEQ),
        "bne" => Some(BNE),
        "blt" => Some(BLT),
        "bge" => Some(BGE),
        "bltu" => Some(BLTU),
        "bgeu" => Some(BGEU),
        "jalr" => Some(JALR),
        "jal" => Some(JAL),
        "lui" => Some(LUI),
        "auipc" => Some(AUIPC),
        "ecall" => Some(ECALL),
        #[cfg(feature = "stack")]
        "call" => Some(CALL),
        #[cfg(feature = "stack")]
        "pop" => Some(POP),
        #[cfg(feature = "stack")]
        "push" => Some(PUSH),
        #[cfg(feature = "stack")]
        "ret" => Some(RET),
        #[cfg(feature = "stack")]
        "callr" => Some(CALLR),
        _ => None,
    }
}
pub fn get_by_opcode(opcode: u32, funct3: u32) -> Option<&'static Instruction> {
    match (opcode, funct3) {
        (0u32, 0u32) => Some(ADD),
        (0u32, 1u32) => Some(SUB),
        (0u32, 2u32) => Some(AND),
        (0u32, 3u32) => Some(OR),
        (0u32, 4u32) => Some(ADDI),
        (0u32, 5u32) => Some(SUBI),
        (0u32, 6u32) => Some(ANDI),
        (0u32, 7u32) => Some(ORI),
        (1u32, 0u32) => Some(XOR),
        (1u32, 1u32) => Some(XNOR),
        (1u32, 2u32) => Some(NAND),
        (1u32, 3u32) => Some(NOR),
        (1u32, 4u32) => Some(XORI),
        (1u32, 5u32) => Some(XNORI),
        (1u32, 6u32) => Some(NANDI),
        (1u32, 7u32) => Some(NORI),
        (2u32, 0u32) => Some(MUL),
        (2u32, 1u32) => Some(MULH),
        (2u32, 2u32) => Some(MULHU),
        (2u32, 3u32) => Some(MULHSU),
        (2u32, 4u32) => Some(MULI),
        (2u32, 5u32) => Some(MULHI),
        (2u32, 6u32) => Some(MULHIU),
        (2u32, 7u32) => Some(MULHISU),
        (3u32, 0u32) => Some(DIV),
        (3u32, 1u32) => Some(REM),
        (3u32, 2u32) => Some(DIVU),
        (3u32, 3u32) => Some(REMU),
        (3u32, 4u32) => Some(DIVI),
        (3u32, 5u32) => Some(REMI),
        (3u32, 6u32) => Some(DIVIU),
        (3u32, 7u32) => Some(REMIU),
        (4u32, 0u32) => Some(SLL),
        (4u32, 1u32) => Some(SRL),
        (4u32, 3u32) => Some(SRA),
        (4u32, 4u32) => Some(ROL),
        (4u32, 5u32) => Some(ROR),
        (5u32, 0u32) => Some(SLLI),
        (5u32, 1u32) => Some(SRLI),
        (5u32, 3u32) => Some(SRAI),
        (5u32, 4u32) => Some(ROLI),
        (5u32, 5u32) => Some(RORI),
        (6u32, 0u32) => Some(SEQ),
        (6u32, 1u32) => Some(SNE),
        (6u32, 2u32) => Some(SLT),
        (6u32, 3u32) => Some(SGE),
        (6u32, 4u32) => Some(SLTU),
        (6u32, 5u32) => Some(SGEU),
        (7u32, 0u32) => Some(SEQI),
        (7u32, 1u32) => Some(SNEI),
        (7u32, 2u32) => Some(SLTI),
        (7u32, 3u32) => Some(SGEI),
        (7u32, 4u32) => Some(SLTIU),
        (7u32, 5u32) => Some(SGEIU),
        (8u32, 0u32) => Some(LW),
        (8u32, 1u32) => Some(LH),
        (8u32, 2u32) => Some(LHU),
        (8u32, 3u32) => Some(LB),
        (8u32, 4u32) => Some(LBU),
        (8u32, 5u32) => Some(SW),
        (8u32, 6u32) => Some(SH),
        (8u32, 7u32) => Some(SB),
        (9u32, 0u32) => Some(BEQ),
        (9u32, 1u32) => Some(BNE),
        (9u32, 2u32) => Some(BLT),
        (9u32, 3u32) => Some(BGE),
        (9u32, 4u32) => Some(BLTU),
        (9u32, 5u32) => Some(BGEU),
        (9u32, 7u32) => Some(JALR),
        (10u32, 0u32) => Some(JAL),
        (11u32, 0u32) => Some(LUI),
        (12u32, 0u32) => Some(AUIPC),
        (32u32, 0u32) => Some(ECALL),
        #[cfg(feature = "stack")]
        (125u32, 0u32) => Some(CALL),
        #[cfg(feature = "stack")]
        (126u32, 0u32) => Some(POP),
        #[cfg(feature = "stack")]
        (126u32, 1u32) => Some(PUSH),
        #[cfg(feature = "stack")]
        (126u32, 2u32) => Some(RET),
        #[cfg(feature = "stack")]
        (126u32, 3u32) => Some(CALLR),
        _ => None,
    }
}
