[package]
name = "archp_assembler"
version = { workspace = true }
edition = { workspace = true }
description = "Assembly implementation of the ArchP ISA"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
inventory = { workspace = true }
nom = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
