[package]
name = "archp_assembler"
version = "0.2.1"
edition = { workspace = true }
description = "Assembly implementation of the ArchP ISA"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[[bin]]
name = "archp_assembler"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
env_logger = { workspace = true }
inventory = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
insta-cmd = { workspace = true }
rand = { workspace = true }
