#:schema _generated/instructions.schema.json

[[opcodes]]
opcode = 0b0000000

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "add", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "sub", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "and", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "or", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "addi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "subi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b110
instruction = { name = "andi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "ori", type = "I" }

[[opcodes]]
opcode = 0b0000001

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "xor", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "xnor", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "nand", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "nor", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "xori", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "xnori", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b110
instruction = { name = "nandi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "nori", type = "I" }

[[opcodes]]
opcode = 0b0000010

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "mul", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "mulh", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "mulhu", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "mulhsu", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "muli", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "mulhi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b110
instruction = { name = "mulhiu", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "mulhisu", type = "I" }

[[opcodes]]
opcode = 0b0000011

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "div", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "rem", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "divu", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "remu", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "divi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "remi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b110
instruction = { name = "diviu", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "remiu", type = "I" }

[[opcodes]]
opcode = 0b0000100

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "sll", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "srl", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "sra", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "rol", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "ror", type = "R" }

[[opcodes]]
opcode = 0b0000101

[[opcodes.funct3s]]
funct3 = 0b000
instruction = {
  name = "slli",
  type = "I",
  format = [{ type = "RegD" }, { type = "RegS" }, { type = "Imm", value = [5, false] }]
}

[[opcodes.funct3s]]
funct3 = 0b001
instruction = {
  name = "srli",
  type = "I",
  format = [{ type = "RegD" }, { type = "RegS" }, { type = "Imm", value = [5, false] }]
}

[[opcodes.funct3s]]
funct3 = 0b011
instruction = {
  name = "srai",
  type = "I",
  format = [{ type = "RegD" }, { type = "RegS" }, { type = "Imm", value = [5, false] }]
}

[[opcodes.funct3s]]
funct3 = 0b100
instruction = {
  name = "roli",
  type = "I",
  format = [{ type = "RegD" }, { type = "RegS" }, { type = "Imm", value = [5, false] }]
}

[[opcodes.funct3s]]
funct3 = 0b101
instruction = {
  name = "rori",
  type = "I",
  format = [{ type = "RegD" }, { type = "RegS" }, { type = "Imm", value = [5, false] }]
}

[[opcodes]]
opcode = 0b0000110

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "seq", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "sne", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "slt", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "sge", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "sltu", type = "R" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "sgeu", type = "R" }

[[opcodes]]
opcode = 0b0000111

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "seqi", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "snei", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "slti", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "sgei", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "sltiu", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "sgeiu", type = "I" }

[[opcodes]]
opcode = 0b0001000

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "lw", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "lh", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "lhu", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "lb", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "lbu", type = "I" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "sw", type = "S" }

[[opcodes.funct3s]]
funct3 = 0b110
instruction = { name = "sh", type = "S" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "sb", type = "S" }

[[opcodes]]
opcode = 0b0001001

[[opcodes.funct3s]]
funct3 = 0b000
instruction = { name = "beq", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b001
instruction = { name = "bne", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b010
instruction = { name = "blt", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b011
instruction = { name = "bge", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b100
instruction = { name = "bltu", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b101
instruction = { name = "bgeu", type = "B" }

[[opcodes.funct3s]]
funct3 = 0b111
instruction = { name = "jalr", type = "I" }

[[opcodes]]
opcode = 0b0001010
instruction = { name = "jal", type = "J" }

[[opcodes]]
opcode = 0b0001011
instruction = { name = "lui", type = "U" }

[[opcodes]]
opcode = 0b0001100
instruction = { name = "auipc", type = "U" }

[[opcodes]]
opcode = 0b0100000

[[opcodes.funct3s]]
funct3 = 0b000
instruction = {
  name = "ecall",
  type = "R",
  format = [{ type = "None" }, { type = "None" }, { type = "None" }]
}

[[opcodes]]
feature = "stack"
opcode = 0b1111101
instruction = {
  name = "call",
  type = "J",
  format = [{ type = "None" }, { type = "Addr", value = 20 }]
}

[[opcodes]]
feature = "stack"
opcode = 0b1111110

[[opcodes.funct3s]]
funct3 = 0b000
instruction = {
  name = "pop",
  type = "I",
  format = [{ type = "RegD" }, { type = "None" }, { type = "None" }]
}

[[opcodes.funct3s]]
funct3 = 0b001
instruction = {
  name = "push",
  type = "I",
  format = [{ type = "None" }, { type = "RegS" }, { type = "None" }]
}

[[opcodes.funct3s]]
funct3 = 0b010
instruction = {
  name = "ret",
  type = "I",
  format = [{ type = "None" }, { type = "None" }, { type = "None" }]
}

[[opcodes.funct3s]]
funct3 = 0b011
instruction = {
  name = "callr",
  type = "I",
  format = [{ type = "None" }, { type = "RegS" }, { type = "Imm", value = [12, true] }]
}
