#!/usr/bin/env fish

source ./scripts/common.fish

argparse h/help s/asm t/trace c/console -- $argv
or return 1

if set -q _flag_help
    echo "Usage: run [options] <file>"
    echo ""
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  -s, --asm       <file> is an assembly file, assemble it before running"
    echo "  -t, --trace     Enable tracing and open the trace viewer after running"
    echo "  -c, --console   Start program on a new virtual terminal"
    return 0
end

set file $argv[1]
if test -z "$file"
    echo_error "Error: No file specified."
    return 1
end
if not test -f "$file"
    echo_error "Error: File '$file' does not exist."
    return 1
end

set -e argv[1]

if set -q _flag_trace
    trap "rm -rf output.bin __dump__.fst .surfer/mappings/Instr" EXIT INT QUIT TERM
else
    trap "rm -rf output.bin" EXIT INT QUIT TERM
end

echo_h1 "Building..."
cargo build --all-features
echo

if set -q _flag_asm
    or string match -q "*.s" $file
    or string match -q "*.asm" $file
    echo_h1 "Assembling..."

    ./target/debug/archp-as $file -o output.bin
    or return 1
    and echo Done

    if set -q _flag_trace
        mkdir -p .surfer/mappings/
        ./target/debug/archp-as $file --hex -o .surfer/mappings/Instr 2>&1 >/dev/null
        sed -i '1i Bits = 32' .surfer/mappings/Instr
    end

    set file output.bin

    echo
end

echo_h1 "Running..."

if test "$argv[1]" = --
    set argv $argv[2..-1]
end

if set -q _flag_trace
    set -a argv -T __dump__.fst
end

if set -q _flag_console
    sudo openvt -sw -- ./target/debug/archp $file -fk $argv
else
    ./target/debug/archp $file $argv
end

if set -q _flag_trace
    echo_h1 "Opening trace viewer..."
    ./scripts/trace __dump__.fst
end
