#!/usr/bin/env fish

source ./scripts/common.fish

# TODO: trace

argparse h/help s/asm -- $argv
or return 1

if set -q _flag_help
    echo "Usage: run [options] <file>"
    echo ""
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  -s, --asm       <file> is an assembly file, assemble it before running"
    return 0
end

set file $argv[1]
if test -z "$file"
    echo_error "Error: No file specified."
    return 1
end
if not test -f "$file"
    echo_error "Error: File '$file' does not exist."
    return 1
end

set -e argv[1]

trap "rm -rf output.bin" EXIT INT QUIT TERM

if set -q _flag_asm
    or string match -q "*.s" $file
    or string match -q "*.asm" $file
    echo_h1 "Assembling..."

    cargo run -p archp_assembler_cli -- $file -o output.bin
    or return 1

    set file output.bin

    echo
end

echo_h1 "Running..."
if test "$argv[1]" = --
    set argv $argv[2..-1]
end
cargo run -p archp_simulator -- $file $argv
echo
