#!/usr/bin/env fish

source ./scripts/common.fish

if command -q surfer
    surfer $argv
else if test -x ./.surfer/surfer
    ./.surfer/surfer $argv
else
    echo_error "Error: surfer not found"
    echo "You can install it globally or locally to '.surfer/surfer'."
    echo "See https://gitlab.com/surfer-project/surfer"
end
