#!/usr/bin/env fish

set base $argv[1]

if test -z "$base"
    echo "Usage: update_schematics <path_to_loacl_game_schematics>"
    return 1
end

set tmpdir (mktemp -d)

mkdir -p $tmpdir/architecture
mkdir -p $tmpdir/component_factory

cp -r $base/architecture/ArchP $tmpdir/architecture/
cp -r $base/component_factory/ArchP $tmpdir/component_factory/

tar -czf ./schematics/ArchP.tar.gz -C $tmpdir .

rm -rf $tmpdir

return 0
